# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nginx', '0002_auto_20170325_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='maintainrealserver',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='realserver',
            name='ip',
        ),
        migrations.AddField(
            model_name='host',
            name='eth00_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Eth0 IP 1'),
        ),
        migrations.AddField(
            model_name='host',
            name='eth01_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Eth0 IP 2'),
        ),
        migrations.AddField(
            model_name='host',
            name='eth10_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Eth1 IP 1'),
        ),
        migrations.AddField(
            model_name='host',
            name='eth11_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Eth1 IP 2'),
        ),
        migrations.AddField(
            model_name='host',
            name='eth20_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Eth2 IP 1'),
        ),
        migrations.AddField(
            model_name='host',
            name='eth21_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Eth2 IP 2'),
        ),
        migrations.AddField(
            model_name='host',
            name='eth30_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Eth3 IP 1'),
        ),
        migrations.AddField(
            model_name='host',
            name='eth31_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Eth3 IP 2'),
        ),
        migrations.AddField(
            model_name='maintainrealserver',
            name='bindip_host_eth',
            field=models.CharField(choices=[('00', 'Eth0.0'), ('01', 'Eth0.1'), ('10', 'Eth1.0'), ('11', 'Eth1.1'), ('20', 'Eth2.0'), ('21', 'Eth2.1'), ('30', 'Eth3.0'), ('31', 'Eth3.1')], default='00', max_length=2, verbose_name='主机服务绑定IP的网卡'),
        ),
        migrations.AddField(
            model_name='realserver',
            name='bindip_host_eth',
            field=models.CharField(choices=[('00', 'Eth0.0'), ('01', 'Eth0.1'), ('10', 'Eth1.0'), ('11', 'Eth1.1'), ('20', 'Eth2.0'), ('21', 'Eth2.1'), ('30', 'Eth3.0'), ('31', 'Eth3.1')], default='00', max_length=2, verbose_name='主机服务绑定IP的网卡'),
        ),
    ]
