# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nginx', '0003_auto_20170328_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='eth00_ip',
            field=models.GenericIPAddressField(default='1.1.1.1', verbose_name='Eth0 IP 1'),
            preserve_default=False,
        ),
    ]
