# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nginx', '0004_auto_20170328_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='eth00_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Eth0 IP 1'),
        ),
    ]
