# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nginx', '0005_auto_20170329_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='site_realserver_status',
            field=models.SmallIntegerField(choices=[(0, '有源站下线'), (1, '全部源站在线'), (2, '状态未知')], default=1, help_text='0:有源站下线  1:全部源站在线  2:状态未知', verbose_name='站点对应的源站聚合状态'),
        ),
    ]
