# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nginx', '0009_myconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BasicConfig',
        ),
        migrations.DeleteModel(
            name='MyConfig',
        ),
    ]
