# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nginx', '0010_auto_20170331_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upstream',
            name='zone',
            field=models.CharField(help_text='zone值必须与nginx配置文件中相应站点的zone相同', max_length=64, unique=True, verbose_name='zone name'),
        ),
    ]
