# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nginx', '0011_auto_20170331_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='eth00_ip',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='Eth0 IP 1'),
        ),
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='主机名'),
        ),
    ]
