# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nginx', '0012_auto_20170331_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxyserver',
            name='ip',
        ),
        migrations.AddField(
            model_name='proxyserver',
            name='bindip_host_eth',
            field=models.CharField(choices=[('00', 'Eth0.0'), ('01', 'Eth0.1'), ('10', 'Eth1.0'), ('11', 'Eth1.1'), ('20', 'Eth2.0'), ('21', 'Eth2.1'), ('30', 'Eth3.0'), ('31', 'Eth3.1')], default='00', max_length=2, verbose_name='主机服务绑定IP的网卡'),
        ),
    ]
