# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 03:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nginx', '0013_auto_20170331_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxyserver',
            name='proxy_server_group',
        ),
    ]
