# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nginx', '0014_remove_proxyserver_proxy_server_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realserver',
            name='upstream',
        ),
        migrations.AddField(
            model_name='site',
            name='real_server',
            field=models.ManyToManyField(blank=True, null=True, related_name='realserver_site', to='nginx.RealServer', verbose_name='源站服务'),
        ),
    ]
