# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 03:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nginx', '0016_realserver_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realserver',
            name='service_port',
        ),
    ]
