# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nginx', '0017_remove_realserver_service_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxyservergroup',
            name='proxy_server',
            field=models.ManyToManyField(blank=True, null=True, related_name='proxyserver_proxyservergroup', to='nginx.ProxyServer', verbose_name='Nginx代理服务实例'),
        ),
    ]
