# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nginx', '0018_proxyservergroup_proxy_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=64, verbose_name='应用实例名')),
                ('note', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
        ),
    ]
