# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nginx', '0019_applytag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintainrealserver',
            name='apply_name',
        ),
        migrations.RemoveField(
            model_name='realserver',
            name='apply_name',
        ),
    ]
