# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nginx', '0020_auto_20170401_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintainrealserver',
            name='apply_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nginx.ApplyTag', verbose_name='应用名'),
        ),
        migrations.AddField(
            model_name='proxyserver',
            name='apply_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nginx.ApplyTag', verbose_name='应用名'),
        ),
        migrations.AddField(
            model_name='realserver',
            name='apply_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nginx.ApplyTag', verbose_name='应用名'),
        ),
    ]
