# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nginx', '0021_auto_20170401_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='site_paginator',
            field=models.IntegerField(default=10, help_text='x个记录分一页', verbose_name='站点展示分页数'),
        ),
    ]
