# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-12 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nginx', '0022_config_site_paginator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': '系统配置', 'verbose_name_plural': '系统配置'},
        ),
        migrations.AddField(
            model_name='site',
            name='site_status',
            field=models.IntegerField(choices=[(0, '运行中'), (1, '维护中')], default=1, help_text='0:暂停  1:开启  初始值为1', verbose_name='站点状态'),
        ),
    ]
