# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-18 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nginx', '0023_auto_20171212_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_status',
            field=models.IntegerField(choices=[(0, '暂停'), (1, '开启')], default=1, help_text='0:暂停  1:开启  初始值为1', verbose_name='站点状态'),
        ),
    ]
